### ISSUE TITLE
Projektbeschreibung

### ISSUE THREAD

**Issue by starfool** [starfool/Labhelp#1]
Ausformulieren der Stichpunkte (Aufgabenstellung und Projektdefinition)
Bis zu einer A4-Seite
Zu verwendende Techniken
Alleinstellungsmerkmal

**Comment by Tiayle** [comment]
Begonnen in Google Drive.

**Comment by Tiayle** [comment]
Soweit beendet, bitte einmal Korrektur lesen.

**Comment by starfool** [comment]
Gelesen und korrigiert (z. B. das Umbenennen als Option eingefügt und nicht als festen Bestandteil).

**Comment by starfool** [comment]
(Versehentlich geschlossen, sorry)
