### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by starfool** [starfool/Labhelp#2]
Mit Prioritäten
Sicht: Dozent, Student, Tutor

**Comment by Tiayle** [comment]
Soweit beendet bis auf "Prioritäten" (?), bitte einmal Korrektur lesen

**Comment by starfool** [comment]
Ich glaube wieder zu wissen, was mit "Prioritäten" gemeint war: Einfach die Funktionen, die vorhanden sein MÜSSEN (Anforderungen) und die Funktionen, die vorhanden sein KÖNNEN (Wünsche, Nice to have) zu verfassen. Vielleicht in Form von "Schön wäre, wenn ich als Student die Möglichkeit hätte..." oder so.
Da fällt mir zunächst auch nur ein, was wir als Nice to have im ersten Log festgehalten hatten:
- Zugriff für alle
- Supersicherheit
- Kalendermäßiges Anlegen von Veranstaltungen

Aber ansonsten habe ich es einmal durchgelesen, Kleinigkeiten korrigiert und für gut befunden. Nur bei dem .csv-Import ist etwas unklar. Habe dafür einen Kommentar im Doc hinterlassen.
