### ISSUE TITLE
Tutor anlegen

### ISSUE THREAD

**Issue by starfool** [starfool/Labhelp#36]
Möglichkeit erschaffen, einen Tutoren einer Veranstaltung hinzuzufügen.

**Comment by starfool** [comment]
Hatten wir uns hier eigentlich geeinigt, ob der Tutor eine E-Mail (mit generiertem Zufallspasswort) erhalten und das Passwort selbst verwalten oder ob der Dozent entsprechend alles anlegen soll?

**Comment by lynxSven** [comment]
Zufalls-Passwort

**Comment by starfool** [comment]
Tutoren können sich selbst anmelden, müssen aber von Dozenten freigeschaltet werden.
